name: CI

on:
  push:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run:  npm install 

      - name: Run Lint
        run:  npm run lint

      - name: Run unit test
        run:  npm test

      - name: Build docker image
        run:  docker build -t simpleapp:latest .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with: 
          image-ref: simpleapp:latest
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Tag and push to Artifact Registry
        run: |
          docker tag simpleapp:latest asia-southeast2-docker.pkg.dev/thinhs-project/my-registry/simpleapp:latest
          docker push asia-southeast2-docker.pkg.dev/thinhs-project/my-registry/simpleapp:latest


